In [1]:
# Dependencies
import requests
from config import ykey
import pandas as pd
import numpy as np

Cities from article '10 best foodie cities in America' on CNBC.
https://www.cnbc.com/2018/11/05/wallethub-best-food-cities-in-america.html

In [2]:
# List of cities
cities = ['Portland, OR', 'San Francisco, CA', 'Miami, FL', 'New York, NY', 'Los Angeles, CA', 'Orlando, FL', 'Las Vegas, NV', 'Seattle, WA', 'San Diego, CA', 'Austin, TX']

cities

['Portland, OR',
 'San Francisco, CA',
 'Miami, FL',
 'New York, NY',
 'Los Angeles, CA',
 'Orlando, FL',
 'Las Vegas, NV',
 'Seattle, WA',
 'San Diego, CA',
 'Austin, TX']

In [3]:
name_list = []
city_list = []
state_list = []
category_list = []
rating_list = []
review_count_list = []
price_list = []

In [4]:
url='https://api.yelp.com/v3/businesses/search'
headers = {'Authorization': 'Bearer %s' % ykey}

for city in cities:
    params = {'location' : city, 'term': 'food', 'limit' : '50', 'sortby' : 'rating, review_count'}
    response = requests.get(url, params, headers=headers)
    data = response.json()
    restaurant_data = data['businesses']
    count = 1

    for restaurant in restaurant_data:
        print(f'Retrieving restaurant {count} in {city}')
        
        for category in restaurant['categories']:
            
            name_list.append(restaurant['name'])
            city_list.append(restaurant['location']['city'])
            state_list.append(restaurant['location']['state'])
            category_list.append(category['title'])
            rating_list.append(restaurant['rating'])
            review_count_list.append(restaurant['review_count'])
            
            try:                
                price_list.append(restaurant['price'])
            
            except:
                price_list.append('')     
            
        count = count + 1

Retrieving restaurant 1 in Portland, OR
Retrieving restaurant 2 in Portland, OR
Retrieving restaurant 3 in Portland, OR
Retrieving restaurant 4 in Portland, OR
Retrieving restaurant 5 in Portland, OR
Retrieving restaurant 6 in Portland, OR
Retrieving restaurant 7 in Portland, OR
Retrieving restaurant 8 in Portland, OR
Retrieving restaurant 9 in Portland, OR
Retrieving restaurant 10 in Portland, OR
Retrieving restaurant 11 in Portland, OR
Retrieving restaurant 12 in Portland, OR
Retrieving restaurant 13 in Portland, OR
Retrieving restaurant 14 in Portland, OR
Retrieving restaurant 15 in Portland, OR
Retrieving restaurant 16 in Portland, OR
Retrieving restaurant 17 in Portland, OR
Retrieving restaurant 18 in Portland, OR
Retrieving restaurant 19 in Portland, OR
Retrieving restaurant 20 in Portland, OR
Retrieving restaurant 21 in Portland, OR
Retrieving restaurant 22 in Portland, OR
Retrieving restaurant 23 in Portland, OR
Retrieving restaurant 24 in Portland, OR
Retrieving restaurant 25 in Portland, OR
Retrieving restaurant 26 in Portland, OR
Retrieving restaurant 27 in Portland, OR
Retrieving restaurant 28 in Portland, OR
Retrieving restaurant 29 in Portland, OR
Retrieving restaurant 30 in Portland, OR
Retrieving restaurant 31 in Portland, OR
Retrieving restaurant 32 in Portland, OR
Retrieving restaurant 33 in Portland, OR
Retrieving restaurant 34 in Portland, OR
Retrieving restaurant 35 in Portland, OR
Retrieving restaurant 36 in Portland, OR
Retrieving restaurant 37 in Portland, OR
Retrieving restaurant 38 in Portland, OR
Retrieving restaurant 39 in Portland, OR
Retrieving restaurant 40 in Portland, OR
Retrieving restaurant 41 in Portland, OR
Retrieving restaurant 42 in Portland, OR
Retrieving restaurant 43 in Portland, OR
Retrieving restaurant 44 in Portland, OR
Retrieving restaurant 45 in Portland, OR
Retrieving restaurant 46 in Portland, OR
Retrieving restaurant 47 in Portland, OR
Retrieving restaurant 48 in Portland, OR
Retrieving restaurant 49 in Portland, OR
Retrieving restaurant 50 in Portland, OR
Retrieving restaurant 1 in San Francisco, CA
Retrieving restaurant 2 in San Francisco, CA
Retrieving restaurant 3 in San Francisco, CA
Retrieving restaurant 4 in San Francisco, CA
Retrieving restaurant 5 in San Francisco, CA
Retrieving restaurant 6 in San Francisco, CA
Retrieving restaurant 7 in San Francisco, CA
Retrieving restaurant 8 in San Francisco, CA
Retrieving restaurant 9 in San Francisco, CA
Retrieving restaurant 10 in San Francisco, CA
Retrieving restaurant 11 in San Francisco, CA
Retrieving restaurant 12 in San Francisco, CA
Retrieving restaurant 13 in San Francisco, CA
Retrieving restaurant 14 in San Francisco, CA
Retrieving restaurant 15 in San Francisco, CA
Retrieving restaurant 16 in San Francisco, CA
Retrieving restaurant 17 in San Francisco, CA
Retrieving restaurant 18 in San Francisco, CA
Retrieving restaurant 19 in San Francisco, CA
Retrieving restaurant 20 in San Francisco, CA
Retrieving restaurant 21 in San Francisco, CA
Retrieving restaurant 22 in San Francisco, CA
Retrieving restaurant 23 in San Francisco, CA
Retrieving restaurant 24 in San Francisco, CA
Retrieving restaurant 25 in San Francisco, CA
Retrieving restaurant 26 in San Francisco, CA
Retrieving restaurant 27 in San Francisco, CA
Retrieving restaurant 28 in San Francisco, CA
Retrieving restaurant 29 in San Francisco, CA
Retrieving restaurant 30 in San Francisco, CA
Retrieving restaurant 31 in San Francisco, CA
Retrieving restaurant 32 in San Francisco, CA
Retrieving restaurant 33 in San Francisco, CA
Retrieving restaurant 34 in San Francisco, CA
Retrieving restaurant 35 in San Francisco, CA
Retrieving restaurant 36 in San Francisco, CA
Retrieving restaurant 37 in San Francisco, CA
Retrieving restaurant 38 in San Francisco, CA
Retrieving restaurant 39 in San Francisco, CA
Retrieving restaurant 40 in San Francisco, CA
Retrieving restaurant 41 in San Francisco, CA
Retrieving restaurant 42 in San Francisco, CA
Retrieving restaurant 43 in San Francisco, CA
Retrieving restaurant 44 in San Francisco, CA
Retrieving restaurant 45 in San Francisco, CA
Retrieving restaurant 46 in San Francisco, CA
Retrieving restaurant 47 in San Francisco, CA
Retrieving restaurant 48 in San Francisco, CA
Retrieving restaurant 49 in San Francisco, CA
Retrieving restaurant 50 in San Francisco, CA
Retrieving restaurant 1 in Miami, FL
Retrieving restaurant 2 in Miami, FL
Retrieving restaurant 3 in Miami, FL
Retrieving restaurant 4 in Miami, FL
Retrieving restaurant 5 in Miami, FL
Retrieving restaurant 6 in Miami, FL
Retrieving restaurant 7 in Miami, FL
Retrieving restaurant 8 in Miami, FL
Retrieving restaurant 9 in Miami, FL
Retrieving restaurant 10 in Miami, FL
Retrieving restaurant 11 in Miami, FL
Retrieving restaurant 12 in Miami, FL
Retrieving restaurant 13 in Miami, FL
Retrieving restaurant 14 in Miami, FL
Retrieving restaurant 15 in Miami, FL
Retrieving restaurant 16 in Miami, FL
Retrieving restaurant 17 in Miami, FL
Retrieving restaurant 18 in Miami, FL
Retrieving restaurant 19 in Miami, FL
Retrieving restaurant 20 in Miami, FL
Retrieving restaurant 21 in Miami, FL
Retrieving restaurant 22 in Miami, FL
Retrieving restaurant 23 in Miami, FL
Retrieving restaurant 24 in Miami, FL
Retrieving restaurant 25 in Miami, FL
Retrieving restaurant 26 in Miami, FL
Retrieving restaurant 27 in Miami, FL
Retrieving restaurant 28 in Miami, FL
Retrieving restaurant 29 in Miami, FL
Retrieving restaurant 30 in Miami, FL
Retrieving restaurant 31 in Miami, FL
Retrieving restaurant 32 in Miami, FL
Retrieving restaurant 33 in Miami, FL
Retrieving restaurant 34 in Miami, FL
Retrieving restaurant 35 in Miami, FL
Retrieving restaurant 36 in Miami, FL
Retrieving restaurant 37 in Miami, FL
Retrieving restaurant 38 in Miami, FL
Retrieving restaurant 39 in Miami, FL
Retrieving restaurant 40 in Miami, FL
Retrieving restaurant 41 in Miami, FL
Retrieving restaurant 42 in Miami, FL
Retrieving restaurant 43 in Miami, FL
Retrieving restaurant 44 in Miami, FL
Retrieving restaurant 45 in Miami, FL
Retrieving restaurant 46 in Miami, FL
Retrieving restaurant 47 in Miami, FL
Retrieving restaurant 48 in Miami, FL
Retrieving restaurant 49 in Miami, FL
Retrieving restaurant 50 in Miami, FL
Retrieving restaurant 1 in New York, NY
Retrieving restaurant 2 in New York, NY
Retrieving restaurant 3 in New York, NY
Retrieving restaurant 4 in New York, NY
Retrieving restaurant 5 in New York, NY
Retrieving restaurant 6 in New York, NY
Retrieving restaurant 7 in New York, NY
Retrieving restaurant 8 in New York, NY
Retrieving restaurant 9 in New York, NY
Retrieving restaurant 10 in New York, NY
Retrieving restaurant 11 in New York, NY
Retrieving restaurant 12 in New York, NY
Retrieving restaurant 13 in New York, NY
Retrieving restaurant 14 in New York, NY
Retrieving restaurant 15 in New York, NY
Retrieving restaurant 16 in New York, NY
Retrieving restaurant 17 in New York, NY
Retrieving restaurant 18 in New York, NY
Retrieving restaurant 19 in New York, NY
Retrieving restaurant 20 in New York, NY
Retrieving restaurant 21 in New York, NY
Retrieving restaurant 22 in New York, NY
Retrieving restaurant 23 in New York, NY
Retrieving restaurant 24 in New York, NY
Retrieving restaurant 25 in New York, NY
Retrieving restaurant 26 in New York, NY
Retrieving restaurant 27 in New York, NY
Retrieving restaurant 28 in New York, NY
Retrieving restaurant 29 in New York, NY
Retrieving restaurant 30 in New York, NY
Retrieving restaurant 31 in New York, NY
Retrieving restaurant 32 in New York, NY
Retrieving restaurant 33 in New York, NY
Retrieving restaurant 34 in New York, NY
Retrieving restaurant 35 in New York, NY
Retrieving restaurant 36 in New York, NY
Retrieving restaurant 37 in New York, NY
Retrieving restaurant 38 in New York, NY
Retrieving restaurant 39 in New York, NY
Retrieving restaurant 40 in New York, NY
Retrieving restaurant 41 in New York, NY
Retrieving restaurant 42 in New York, NY
Retrieving restaurant 43 in New York, NY
Retrieving restaurant 44 in New York, NY
Retrieving restaurant 45 in New York, NY
Retrieving restaurant 46 in New York, NY
Retrieving restaurant 47 in New York, NY
Retrieving restaurant 48 in New York, NY
Retrieving restaurant 49 in New York, NY
Retrieving restaurant 50 in New York, NY

Retrieving restaurant 1 in Los Angeles, CA
Retrieving restaurant 2 in Los Angeles, CA
Retrieving restaurant 3 in Los Angeles, CA
Retrieving restaurant 4 in Los Angeles, CA
Retrieving restaurant 5 in Los Angeles, CA
Retrieving restaurant 6 in Los Angeles, CA
Retrieving restaurant 7 in Los Angeles, CA
Retrieving restaurant 8 in Los Angeles, CA
Retrieving restaurant 9 in Los Angeles, CA
Retrieving restaurant 10 in Los Angeles, CA
Retrieving restaurant 11 in Los Angeles, CA
Retrieving restaurant 12 in Los Angeles, CA
Retrieving restaurant 13 in Los Angeles, CA
Retrieving restaurant 14 in Los Angeles, CA
Retrieving restaurant 15 in Los Angeles, CA
Retrieving restaurant 16 in Los Angeles, CA
Retrieving restaurant 17 in Los Angeles, CA
Retrieving restaurant 18 in Los Angeles, CA
Retrieving restaurant 19 in Los Angeles, CA
Retrieving restaurant 20 in Los Angeles, CA
Retrieving restaurant 21 in Los Angeles, CA
Retrieving restaurant 22 in Los Angeles, CA
Retrieving restaurant 23 in Los Angeles, CA
Retrieving restaurant 24 in Los Angeles, CA
Retrieving restaurant 25 in Los Angeles, CA
Retrieving restaurant 26 in Los Angeles, CA
Retrieving restaurant 27 in Los Angeles, CA
Retrieving restaurant 28 in Los Angeles, CA
Retrieving restaurant 29 in Los Angeles, CA
Retrieving restaurant 30 in Los Angeles, CA
Retrieving restaurant 31 in Los Angeles, CA
Retrieving restaurant 32 in Los Angeles, CA
Retrieving restaurant 33 in Los Angeles, CA
Retrieving restaurant 34 in Los Angeles, CA
Retrieving restaurant 35 in Los Angeles, CA
Retrieving restaurant 36 in Los Angeles, CA
Retrieving restaurant 37 in Los Angeles, CA
Retrieving restaurant 38 in Los Angeles, CA
Retrieving restaurant 39 in Los Angeles, CA
Retrieving restaurant 40 in Los Angeles, CA
Retrieving restaurant 41 in Los Angeles, CA
Retrieving restaurant 42 in Los Angeles, CA
Retrieving restaurant 43 in Los Angeles, CA
Retrieving restaurant 44 in Los Angeles, CA
Retrieving restaurant 45 in Los Angeles, CA
Retrieving restaurant 46 in Los Angeles, CA
Retrieving restaurant 47 in Los Angeles, CA
Retrieving restaurant 48 in Los Angeles, CA
Retrieving restaurant 49 in Los Angeles, CA
Retrieving restaurant 50 in Los Angeles, CA
Retrieving restaurant 1 in Orlando, FL
Retrieving restaurant 2 in Orlando, FL
Retrieving restaurant 3 in Orlando, FL
Retrieving restaurant 4 in Orlando, FL
Retrieving restaurant 5 in Orlando, FL
Retrieving restaurant 6 in Orlando, FL
Retrieving restaurant 7 in Orlando, FL
Retrieving restaurant 8 in Orlando, FL
Retrieving restaurant 9 in Orlando, FL
Retrieving restaurant 10 in Orlando, FL
Retrieving restaurant 11 in Orlando, FL
Retrieving restaurant 12 in Orlando, FL
Retrieving restaurant 13 in Orlando, FL
Retrieving restaurant 14 in Orlando, FL
Retrieving restaurant 15 in Orlando, FL
Retrieving restaurant 16 in Orlando, FL
Retrieving restaurant 17 in Orlando, FL
Retrieving restaurant 18 in Orlando, FL
Retrieving restaurant 19 in Orlando, FL
Retrieving restaurant 20 in Orlando, FL
Retrieving restaurant 21 in Orlando, FL
Retrieving restaurant 22 in Orlando, FL
Retrieving restaurant 23 in Orlando, FL
Retrieving restaurant 24 in Orlando, FL
Retrieving restaurant 25 in Orlando, FL
Retrieving restaurant 26 in Orlando, FL
Retrieving restaurant 27 in Orlando, FL
Retrieving restaurant 28 in Orlando, FL
Retrieving restaurant 29 in Orlando, FL
Retrieving restaurant 30 in Orlando, FL
Retrieving restaurant 31 in Orlando, FL
Retrieving restaurant 32 in Orlando, FL
Retrieving restaurant 33 in Orlando, FL
Retrieving restaurant 34 in Orlando, FL
Retrieving restaurant 35 in Orlando, FL
Retrieving restaurant 36 in Orlando, FL
Retrieving restaurant 37 in Orlando, FL
Retrieving restaurant 38 in Orlando, FL
Retrieving restaurant 39 in Orlando, FL
Retrieving restaurant 40 in Orlando, FL
Retrieving restaurant 41 in Orlando, FL
Retrieving restaurant 42 in Orlando, FL
Retrieving restaurant 43 in Orlando, FL
Retrieving restaurant 44 in Orlando, FL
Retrieving restaurant 45 in Orlando, FL
Retrieving restaurant 46 in Orlando, FL
Retrieving restaurant 47 in Orlando, FL
Retrieving restaurant 48 in Orlando, FL
Retrieving restaurant 49 in Orlando, FL
Retrieving restaurant 50 in Orlando, FL
Retrieving restaurant 1 in Las Vegas, NV
Retrieving restaurant 2 in Las Vegas, NV
Retrieving restaurant 3 in Las Vegas, NV
Retrieving restaurant 4 in Las Vegas, NV
Retrieving restaurant 5 in Las Vegas, NV
Retrieving restaurant 6 in Las Vegas, NV
Retrieving restaurant 7 in Las Vegas, NV
Retrieving restaurant 8 in Las Vegas, NV
Retrieving restaurant 9 in Las Vegas, NV
Retrieving restaurant 10 in Las Vegas, NV
Retrieving restaurant 11 in Las Vegas, NV
Retrieving restaurant 12 in Las Vegas, NV
Retrieving restaurant 13 in Las Vegas, NV
Retrieving restaurant 14 in Las Vegas, NV
Retrieving restaurant 15 in Las Vegas, NV
Retrieving restaurant 16 in Las Vegas, NV
Retrieving restaurant 17 in Las Vegas, NV
Retrieving restaurant 18 in Las Vegas, NV
Retrieving restaurant 19 in Las Vegas, NV
Retrieving restaurant 20 in Las Vegas, NV
Retrieving restaurant 21 in Las Vegas, NV
Retrieving restaurant 22 in Las Vegas, NV
Retrieving restaurant 23 in Las Vegas, NV
Retrieving restaurant 24 in Las Vegas, NV
Retrieving restaurant 25 in Las Vegas, NV
Retrieving restaurant 26 in Las Vegas, NV
Retrieving restaurant 27 in Las Vegas, NV
Retrieving restaurant 28 in Las Vegas, NV
Retrieving restaurant 29 in Las Vegas, NV
Retrieving restaurant 30 in Las Vegas, NV
Retrieving restaurant 31 in Las Vegas, NV
Retrieving restaurant 32 in Las Vegas, NV
Retrieving restaurant 33 in Las Vegas, NV
Retrieving restaurant 34 in Las Vegas, NV
Retrieving restaurant 35 in Las Vegas, NV
Retrieving restaurant 36 in Las Vegas, NV
Retrieving restaurant 37 in Las Vegas, NV
Retrieving restaurant 38 in Las Vegas, NV
Retrieving restaurant 39 in Las Vegas, NV
Retrieving restaurant 40 in Las Vegas, NV
Retrieving restaurant 41 in Las Vegas, NV
Retrieving restaurant 42 in Las Vegas, NV
Retrieving restaurant 43 in Las Vegas, NV
Retrieving restaurant 44 in Las Vegas, NV
Retrieving restaurant 45 in Las Vegas, NV
Retrieving restaurant 46 in Las Vegas, NV
Retrieving restaurant 47 in Las Vegas, NV
Retrieving restaurant 48 in Las Vegas, NV
Retrieving restaurant 49 in Las Vegas, NV
Retrieving restaurant 50 in Las Vegas, NV
Retrieving restaurant 1 in Seattle, WA
Retrieving restaurant 2 in Seattle, WA
Retrieving restaurant 3 in Seattle, WA
Retrieving restaurant 4 in Seattle, WA
Retrieving restaurant 5 in Seattle, WA
Retrieving restaurant 6 in Seattle, WA
Retrieving restaurant 7 in Seattle, WA
Retrieving restaurant 8 in Seattle, WA
Retrieving restaurant 9 in Seattle, WA
Retrieving restaurant 10 in Seattle, WA
Retrieving restaurant 11 in Seattle, WA
Retrieving restaurant 12 in Seattle, WA
Retrieving restaurant 13 in Seattle, WA
Retrieving restaurant 14 in Seattle, WA
Retrieving restaurant 15 in Seattle, WA
Retrieving restaurant 16 in Seattle, WA
Retrieving restaurant 17 in Seattle, WA
Retrieving restaurant 18 in Seattle, WA
Retrieving restaurant 19 in Seattle, WA
Retrieving restaurant 20 in Seattle, WA
Retrieving restaurant 21 in Seattle, WA
Retrieving restaurant 22 in Seattle, WA
Retrieving restaurant 23 in Seattle, WA
Retrieving restaurant 24 in Seattle, WA
Retrieving restaurant 25 in Seattle, WA
Retrieving restaurant 26 in Seattle, WA
Retrieving restaurant 27 in Seattle, WA
Retrieving restaurant 28 in Seattle, WA
Retrieving restaurant 29 in Seattle, WA
Retrieving restaurant 30 in Seattle, WA
Retrieving restaurant 31 in Seattle, WA
Retrieving restaurant 32 in Seattle, WA
Retrieving restaurant 33 in Seattle, WA
Retrieving restaurant 34 in Seattle, WA
Retrieving restaurant 35 in Seattle, WA
Retrieving restaurant 36 in Seattle, WA
Retrieving restaurant 37 in Seattle, WA
Retrieving restaurant 38 in Seattle, WA
Retrieving restaurant 39 in Seattle, WA
Retrieving restaurant 40 in Seattle, WA
Retrieving restaurant 41 in Seattle, WA
Retrieving restaurant 42 in Seattle, WA
Retrieving restaurant 43 in Seattle, WA
Retrieving restaurant 44 in Seattle, WA
Retrieving restaurant 45 in Seattle, WA
Retrieving restaurant 46 in Seattle, WA
Retrieving restaurant 47 in Seattle, WA
Retrieving restaurant 48 in Seattle, WA
Retrieving restaurant 49 in Seattle, WA
Retrieving restaurant 50 in Seattle, WA

Retrieving restaurant 1 in San Diego, CA
Retrieving restaurant 2 in San Diego, CA
Retrieving restaurant 3 in San Diego, CA
Retrieving restaurant 4 in San Diego, CA
Retrieving restaurant 5 in San Diego, CA
Retrieving restaurant 6 in San Diego, CA
Retrieving restaurant 7 in San Diego, CA
Retrieving restaurant 8 in San Diego, CA
Retrieving restaurant 9 in San Diego, CA
Retrieving restaurant 10 in San Diego, CA
Retrieving restaurant 11 in San Diego, CA
Retrieving restaurant 12 in San Diego, CA
Retrieving restaurant 13 in San Diego, CA
Retrieving restaurant 14 in San Diego, CA
Retrieving restaurant 15 in San Diego, CA
Retrieving restaurant 16 in San Diego, CA
Retrieving restaurant 17 in San Diego, CA
Retrieving restaurant 18 in San Diego, CA
Retrieving restaurant 19 in San Diego, CA
Retrieving restaurant 20 in San Diego, CA
Retrieving restaurant 21 in San Diego, CA
Retrieving restaurant 22 in San Diego, CA
Retrieving restaurant 23 in San Diego, CA
Retrieving restaurant 24 in San Diego, CA
Retrieving restaurant 25 in San Diego, CA
Retrieving restaurant 26 in San Diego, CA
Retrieving restaurant 27 in San Diego, CA
Retrieving restaurant 28 in San Diego, CA
Retrieving restaurant 29 in San Diego, CA
Retrieving restaurant 30 in San Diego, CA
Retrieving restaurant 31 in San Diego, CA
Retrieving restaurant 32 in San Diego, CA
Retrieving restaurant 33 in San Diego, CA
Retrieving restaurant 34 in San Diego, CA
Retrieving restaurant 35 in San Diego, CA
Retrieving restaurant 36 in San Diego, CA
Retrieving restaurant 37 in San Diego, CA
Retrieving restaurant 38 in San Diego, CA
Retrieving restaurant 39 in San Diego, CA
Retrieving restaurant 40 in San Diego, CA
Retrieving restaurant 41 in San Diego, CA
Retrieving restaurant 42 in San Diego, CA
Retrieving restaurant 43 in San Diego, CA
Retrieving restaurant 44 in San Diego, CA
Retrieving restaurant 45 in San Diego, CA
Retrieving restaurant 46 in San Diego, CA
Retrieving restaurant 47 in San Diego, CA
Retrieving restaurant 48 in San Diego, CA
Retrieving restaurant 49 in San Diego, CA
Retrieving restaurant 50 in San Diego, CA
Retrieving restaurant 1 in Austin, TX
Retrieving restaurant 2 in Austin, TX
Retrieving restaurant 3 in Austin, TX
Retrieving restaurant 4 in Austin, TX
Retrieving restaurant 5 in Austin, TX
Retrieving restaurant 6 in Austin, TX
Retrieving restaurant 7 in Austin, TX
Retrieving restaurant 8 in Austin, TX
Retrieving restaurant 9 in Austin, TX
Retrieving restaurant 10 in Austin, TX
Retrieving restaurant 11 in Austin, TX
Retrieving restaurant 12 in Austin, TX
Retrieving restaurant 13 in Austin, TX
Retrieving restaurant 14 in Austin, TX
Retrieving restaurant 15 in Austin, TX
Retrieving restaurant 16 in Austin, TX
Retrieving restaurant 17 in Austin, TX
Retrieving restaurant 18 in Austin, TX
Retrieving restaurant 19 in Austin, TX
Retrieving restaurant 20 in Austin, TX
Retrieving restaurant 21 in Austin, TX
Retrieving restaurant 22 in Austin, TX
Retrieving restaurant 23 in Austin, TX
Retrieving restaurant 24 in Austin, TX
Retrieving restaurant 25 in Austin, TX
Retrieving restaurant 26 in Austin, TX
Retrieving restaurant 27 in Austin, TX
Retrieving restaurant 28 in Austin, TX
Retrieving restaurant 29 in Austin, TX
Retrieving restaurant 30 in Austin, TX
Retrieving restaurant 31 in Austin, TX
Retrieving restaurant 32 in Austin, TX
Retrieving restaurant 33 in Austin, TX
Retrieving restaurant 34 in Austin, TX
Retrieving restaurant 35 in Austin, TX
Retrieving restaurant 36 in Austin, TX
Retrieving restaurant 37 in Austin, TX
Retrieving restaurant 38 in Austin, TX
Retrieving restaurant 39 in Austin, TX
Retrieving restaurant 40 in Austin, TX
Retrieving restaurant 41 in Austin, TX
Retrieving restaurant 42 in Austin, TX
Retrieving restaurant 43 in Austin, TX
Retrieving restaurant 44 in Austin, TX
Retrieving restaurant 45 in Austin, TX
Retrieving restaurant 46 in Austin, TX
Retrieving restaurant 47 in Austin, TX
Retrieving restaurant 48 in Austin, TX
Retrieving restaurant 49 in Austin, TX
Retrieving restaurant 50 in Austin, TX

In [5]:
# Create DataFrame
restaurants_pd = pd.DataFrame({'Name' : name_list, 'City' : city_list, 'State' : state_list, 'Category' : category_list, 
                               'Rating' : rating_list, 'Review Count' : review_count_list, 'Price' : price_list})

restaurants_pd.head()

,Name,City,State,Category,Rating,Review Count,Price
0,Screen Door,Portland,OR,Southern,4.5,6369,$$
1,Screen Door,Portland,OR,Cajun/Creole,4.5,6369,$$
2,Screen Door,Portland,OR,Breakfast & Brunch,4.5,6369,$$
3,Tasty n Alder,Portland,OR,American (New),4.5,3463,$$
4,Tasty n Alder,Portland,OR,Breakfast & Brunch,4.5,3463,$$

In [17]:
# len(restaurants_pd)

restaurants_pd['Price'] = restaurants_pd['Price'].replace({'$$$$$' : '5', '$$$$' : '4', '$$$' : 3, '$$' : '2', '$' : 1})

portland_pd = restaurants_pd[restaurants_pd.City == 'Portland']
sanfrancisco_pd = restaurants_pd[restaurants_pd.City == 'San Francisco']
miami_pd = restaurants_pd[restaurants_pd.City == 'Miami']
newyork_pd = restaurants_pd[restaurants_pd.City == 'New York']
losangeles_pd = restaurants_pd[restaurants_pd.City == 'Los Angeles']
orlando_pd = restaurants_pd[restaurants_pd.City == 'Orlando']
lasvegas_pd = restaurants_pd[restaurants_pd.City == 'Las Vegas']
seattle_pd = restaurants_pd[restaurants_pd.City == 'Seattle']
sandiego_pd = restaurants_pd[restaurants_pd.City == 'San Diego']
austin_pd = restaurants_pd[restaurants_pd.City == 'Austin']

In [18]:
portland_pd.head()

,Name,City,State,Category,Rating,Review Count,Price
0,Screen Door,Portland,OR,Southern,4.5,6369,2
1,Screen Door,Portland,OR,Cajun/Creole,4.5,6369,2
2,Screen Door,Portland,OR,Breakfast & Brunch,4.5,6369,2
3,Tasty n Alder,Portland,OR,American (New),4.5,3463,2
4,Tasty n Alder,Portland,OR,Breakfast & Brunch,4.5,3463,2